name: Store/Retrieve value
description: Single key/value store
inputs:
  action:
    description: Get or set the value of a key
    required: true
    default: get
  key:
    description: name of key
    required: true
  value:
    description: value assigned to the key
    required: false
outputs:
  value:
    description: Value of key if available and requested "get"
    value: ${{ steps.get-value.outputs.value }}
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: key-value-store-get
      with:
        path: ${{ inputs.key }}
        key: ${{ inputs.key }}-store
    - name: get value
      id: get-value
      if: ${{ inputs.action == 'get' }}
      env:
        FILE_NAME: ${{inputs.key}}
      run: echo "value=$(cat ${FILE_NAME})" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: set value
      if: ${{ inputs.action == 'set' }}
      env:
        VALUE: ${{inputs.value}}
        FILE_NAME: ${{inputs.key}}
      run: echo ${VALUE} > ${FILE_NAME}
      shell: bash

