on: [push]

jobs:
  retrieve_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - id: foo
      uses: ./
      with:
        action: get
        key: commit-sha
        value: ${{ github.sha }}
