on: [push]

jobs:
  retrieve_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: test
      uses: ./
      with:
        action: get
        key: commit-sha
        value: ${{ github.sha }}
