on: [push]

jobs:
  retrieve_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Testing get
      id: get
      uses: ./
      with:
        action: get
        key: commit-sha
        value: ${{ github.sha }}
    - name: Show last value
      env:
        SHA: ${{ steps.get.output.value }}
      run: ls && echo Value is ${SHA}
    - name: Testing set
      uses: ./
      with:
        action: set
        key: commit-sha
        value: ${{ github.sha }}
